### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by iver56** [kwsp/fftconv#1]
I came across your repo and thought it looks useful. I also noticed that there isn't a license file in the repository.

Could you please add a license? If you're open to suggestions, I would recommend a permissive license like the MIT License (if possible), which would allow others to use, modify, and distribute your code while providing credit back to you.

Here is a link that could help you choose an open source license: https://choosealicense.com/

**Comment by kwsp** [comment]
Thanks, I added the MIT license! (Although I'm not sure about the legality of it given `fftw` uses GPL.

I originally wrote this with `fftw` to support fast convolution in a large internal code base, and decided to open source this part. Recently (or not so recently), I got approval from the SciPy developers to work on merging a native implementation of Overlap-Add fast convolution into SciPy. However, SciPy uses a version of `pocketfft` due to `fftw` being GPL licensed. So I started porting my code to use recent versions of the `pocketfft` libraries (C and C++ versions), but the performance I got is way worse than `fftw`. I would appreciate any insight or suggestions to improve the performance of any implementations here!

**Comment by iver56** [comment]
Thanks!

Yeah, I get it, the GPL licences complicate things. I don't know anything about pocketfft, but I tried to look up fftw alternatives, and I found https://github.com/project-gemmi/benchmarking-fft which links to https://github.com/Themaister/muFFT and https://www.shoup.net/PGFFT/ and https://bitbucket.org/jpommier/pffft/ which are supposed to be simpler alternatives with comparable performance and more permissive license. Could that be worth exploring?

If this is the pocketfft you were refering to: https://github.com/hayguen/pocketfft maybe it is not the best option? I mean it isn't so popular, and it has no commits for the last two years
